name: Publish to NPM

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: "1.77.2"

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: "client_tests/.nvmrc"
          registry-url: "https://registry.npmjs.org"

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Check format
        run: cargo fmt --check

      #- name: Lint via Clippy
      #  run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run vanilla tests
        run: cargo test

      - name: Run full tests
        run: cargo test --all-features

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Run web tests
        run: wasm-pack test --chrome --headless --release

      - name: Build wasm
        run: wasm-pack build --scope giancosta86 --release --target web

      - name: Update package.json
        working-directory: pkg
        run: |
          jq '. + {publishConfig: {access: "public"}}' package.json > tmp.json && mv tmp.json package.json

      - name: Install pkg dependencies
        working-directory: pkg
        run: yarn install

      - name: Perform client-side tests
        working-directory: client_tests
        run: yarn && yarn test

      - name: Publish NPM package
        working-directory: pkg
        run: yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
