name: Verify

on:
  pull_request:
    types: [opened, synchronize]
    branches: main

jobs:
  verify:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - uses: giancosta86/aurora-github/actions/verify-rust-wasm@v12
        with:
          wasm-pack-version: 0.15.0
          npm-scope: giancosta86
          node-version: 26.2.0
          package-manager: pnpm@10.22.0
